////////////////////////////////////////////////////////////////////////////////
// Author: Juan Luis Suarez Diaz
// Jun, 2015
// Dropbox MSN
////////////////////////////////////////////////////////////////////////////////
package GUI;

import Model.User;
import Model.UserState;
import java.awt.Color;

/**
 *
 * @author Juan Luis
 */
public class UserView extends javax.swing.JPanel {

    private User userModel;
    
    private boolean isSelected;
    
    /**
     * Private method to set colors.
     * @param c Color to set.
     */
    private void setTextColors(Color c){
        this.labelName.setForeground(c);
        this.labelState.setForeground(c);
        this.labelDate.setForeground(c);
    }
    
    private void setBackground(){
        if(isSelected){
            this.setBackground(new Color(0x00FFFF));
        }
        else{
            this.setBackground(new Color(0xF0F0F0));
        }
    }
    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
        isSelected = false;
    }
    
    /**
     * Get the user
     * @return Model User.
     */
    public User getUser(){
        return userModel;
    }
    
    /**
     * @return true if and only if the user is selected.
     */
    public boolean isSelected(){
        return isSelected;
    }
    
    /**
     * Set the view with a user.
     * @param u User.
     */
    public void setUser(User u){
        this.userModel = u;
        if(userModel.getState() == UserState.OFF){
            this.setVisible(false);
        }
        else{
            this.setVisible(true);
            if(userModel.getState() == UserState.ONLINE)
                this.setTextColors(Color.GREEN);
            else if(userModel.getState() == UserState.ABSENT)
                this.setTextColors(Color.ORANGE);
            else if (userModel.getState() == UserState.BUSY)
                this.setTextColors(Color.RED);
        }
        repaint();
    }

    @Override
    public void setVisible(boolean bln){
        super.setVisible(bln);
        isSelected = false;
        setBackground();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(139, 89));
        setMinimumSize(new java.awt.Dimension(139, 89));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Usuario");

        labelState.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelState.setText("ONLINE");

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDate.setText("31/07/1995 13:30:00");
        labelDate.setToolTipText("Última actualización (Last update).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelState, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        isSelected = !isSelected;
        setBackground();
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
